In [1]:
import torch
from sentence_transformers import SentenceTransformer, InputExample, losses
from sentence_transformers.evaluation import EmbeddingSimilarityEvaluator, SimilarityFunction
from torch.utils.data import DataLoader
from datasets import load_dataset
import pandas as pd
from sklearn.model_selection import train_test_split

/raid/deallab/anaconda3/envs/djk/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [ ]:
model_path = "fine_tuned_model"

# 모델 로드
model = SentenceTransformer(model_path)

# 모델을 GPU로 이동 (가능한 경우)
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

In [3]:
# parquet 파일 로드
file_path = '/raid/deallab/SF_RAG_Data/ASQA/dev.parquet'
df = pd.read_parquet(file_path)

# 데이터 확인
df.head()

,ambiguous_question,qa_pairs,wikipages,annotations,sample_id
0,Who has the highest goals in world football?,"[{'context': 'No context provided', 'question'...",[{'title': 'International Federation of Footba...,"[{'knowledge': [], 'long_answer': 'Ali Dael ha...",-7013890438520559398
1,Who is the original artist of sound of silence?,[{'context': 'Sounds of Silence is the second ...,"[{'title': 'The Sound of Silence', 'url': 'htt...",[{'knowledge': [{'content': 'Wednesday Morning...,7089015503030534342
2,When was the first apple i phone made?,"[{'context': 'On January 9, 2007, Steve Jobs a...","[{'title': 'iPhone (1st generation)', 'url': '...",[{'knowledge': [{'content': 'The iPhone was re...,8793099883447006698
3,Who played the weasley brothers in harry potter?,[{'context': 'Richard Fish appeared as Bill br...,"[{'title': 'List of Harry Potter characters', ...",[{'knowledge': [{'content': 'Dozens of actors ...,-881464876144297194
4,How many state parks are there in virginia?,"[{'context': 'No context provided', 'question'...","[{'title': 'List of Virginia state parks', 'ur...",[{'knowledge': [{'content': 'Virginia opened i...,1650309494326541834

In [13]:
dif_questions=[]
for i in range(len(df)):
    res=[]
    for data in df['qa_pairs'][i]:
        res.append(data['question'])
    dif_questions.append(res)

In [14]:
dif_questions

[["Who has the highest goals in men's world international football?",
  "Who has the highest goals all-time in men's football?",
  "Who has the highest goals in women's world international football?"],
 ['Who is the original artist of sound of silence, the song, released in 1964?',
  'Who is the original artist of sound of silence, the album?',
  'Who is the original artist of sound of silence, the song, released in 2016?'],
 ['When was the first apple i phone released?',
  'When was the first apple i phone for beta testing made?',
  'When was the first apple i phone 1 made?',
  'When was the first apple i phone beta made?'],
 ['Who played  Bill weasley in Harry Potter and the Prisoner of Azkaban?',
  'Who played percy weasley in harry potter?',
  'Who played fred weasley in harry potter?',
  'Who played ron weasley in harry potter?',
  'Who played george weasley in harry potter?',
  'Who played  Bill weasley in harry potter (2001-2011)?'],
 ['How many state parks are there in virginia in 1936?',
  'How many state parks are there in virginia in 2016?',
  'How many state parks were there when the state park system formed in Virginia?',
  'How many state parks were there in Virginia as of 2016?'],
 ['Who are the teams that performed in competition at the champions league final 2018?',
  'Who performed best at the champions league final 2018, winning man of the match?',
  'Who performed at the opening ceremony of the champions league final 2018?',
  'Who performed the anthem at the champions league final 2018?'],
 ['Which character killed the man in thelma and louise?',
  'Which actor killed the man in thelma and louise?',
  'Who is the character that kills Harlan in the film Thelma and Louise?',
  'Who is the actor of the character that killed a man in the film Thelma and Louise?'],
 ["Who does Charlie Day play on It's Always Sunny in Philadelphia?",
  "Who plays Charlie Kelly on It's Always Sunny in Philadelphia?"],
 ['As of 2017, how many times have the lakers won the finals?',
  'As of 2016, how many times have the Lakers won the finals?',
  'As of 2015, how many times have the Lakers won the finals?'],
 ['How many states plus territories in india are under congress?',
  'How many states alone in india are under congress?'],
 ['Who played fruma sarah in the 1971 film, Fiddler on the Roof?',
  'Who played Fruma Sarah in the original 1964 Broadway cast of Fiddler on the Roof?',
  'Who is the character of Fruma Sarah in Fiddler on the Roof?',
  'Who played Fruma Sarah in the 2015-2016 Broadway Revival of Fiddler on the Roof?'],
 ['What date did toronto host the mlb all-star game?',
  'Which all-star game did toronto host?'],
 ['What kind of car in to catch a thief in terms of model?',
  'What kind of car in to catch a thief in terms of automobile make?'],
 ['When did season 4 of jersey shore first air?',
  'When did season 4 of jersey shore last air?',
  'When did season 5 of jersey shore first air?',
  'When did season 5 of jersey shore last air?',
  'When did season 6 of jersey shore first air?',
  'When did season 6 of jersey shore last air?'],
 ["What season of Grey's Anatomy was the plane crash involving six doctors?",
  "What season of Grey's Anatomy was the plane crash in Seattle that brought memories of a previous plane crash?",
  "What season of Grey's Anatomy was the plane crash that claimed the life of Lexie Grey?",
  "What season of Grey's Anatomy was the plane crash in downtown Seattle?"],
 ['As per the March 2018-2019 report, what is the number of branches of oriental bank of commerce in india?',
  'What is the number of branches of oriental bank of commerce in india after amalgamation of Global Trust Bank?',
  'Number of branches of oriental bank of commerce in india after expected merger with United Bank of India in 2020?'],
 ['In what year did the rams go to St. Louis?',
  'What was the first game the Rams played in St. Louis?'],
 ['When did the first wave of voortrekkers arrive in south africa?',
  'When did the voortrekkers exploratory treks arrive in south africa?'],
 ['Who plays patrick in  the 1999 film 10 things i hate about you?',
  'Who plays patrick in the 2009 tv series 10 things i hate about you?',
  'Who plays patrick in the film 10 things i hate about you?',
  'Who plays patrick in the TV series 10 things i hate about you?'],
 ['Microsoft live movie maker is an example of a freely licensed software, often called free what?',
  'Microsoft live movie maker is an example of free software used for what purpose?'],
 ['Who is the 17th Chief Minister of MP?',
  'Who is the 16th Chief Minister of MP?',
  'Who is the 15th Chief Minister of MP?',
  'Who is the 17th chief minister of m. p?',
  'Who is the 16th chief minister of m. p?',
  'Who is the 15th chief minister of m. p?'],
 ['Which band sings the 1973 song "Stuck in the Middle with You"?',
  'Who sings the lead vocals in the 1973 song "Stuck in the Middle with You"?',
  'Who sings harmony in the 1973 song "Stuck in the Middle with You"?',
  'Who sings the 2004 song "Stuck in the  Middle"?',
  'Who sings the theme song for the TV show Stuck in the Middle?'],
 ['How many competitive Grammy Awards does Whitney Houston have?',
  'How many Grammy Hall of Fame Awards does Whitney Houston have?',
  'How many total Grammy Awards does Whitney Houston have?'],
 ['When was non-commercial amounts of crude oil first discovered in nigeria?',
  'When was commerical amounts of crude oil first discovered in nigeria?'],
 ['When was the first Fast and Furious film created?|When was the first movie in The Fast Saga series filmed?',
  'When was the first fast and furious film released?|When was the first of the fast and the furious films released?'],
 ['Who originally sang "I\'m Coming Out"?',
  'Who sang an official 2003 cover of "I\'m Coming Out"?'],
 ['When is episode 113 of dragon ball super coming out for its original airdate?',
  'When is episode 113 of dragon ball super coming out for its american airdate?',
  'When is episode 113 of dragon ball super coming out originally?',
  'When is episode 113 of dragon ball super coming out in America?'],
 ['Who is traditionally said to have written 2 Thessalonians?',
  'Who do many modern scholars argue wrote 2 Thessalonians?',
  'Who do most scholars say wrote 1 Thessalonians?'],
 ['When is fortnite battle royale beta version being released on android for samsung devices exclusively?',
  'When is fortnite battle royale beta version being released on android for non-Samsung devices?',
  'When is fortnite battle royale being released on android to all without an invite?'],
 ['How many gold medals did Australia win in the 200 Olympics?',
  'How many silver medals did Australia win in the 2000 Olympics?',
  'How many bronze medals did Australia win in the 2000 Olympics?',
  'How many total medals did Australia win in the 2000 Olympics?'],
 ['Who is elected as the vice president of india in 2017?',
  'Who is elected as the vice president of india in 2012?',
  'Who is elected as the vice president of india in 2007?',
  'Who was elected as the Vice President of India in 2017?',
  'Who was elected as the Vice President of India in 2007 and 2012?',
  'Who was elected as the Vice President of India in 2002?'],
 ["Who was england's prime minister at the start of ww1?",
  "Who was england's prime minister at the end of ww1?",
  "Who was England's prime minister at the beginning of WWI?",
  "Who was England's prime minister at the end of WWI?"],
 ['Who played Snowman in the original Smokey and the Bandit?',
  'Who played Snowman in the Smokey and the Bandit II?',
  'Who played Snowman in the Smokey and the Bandit Part 3?'],
 ['Who beat villanova in 2017 in the ncaa tournament?',
  'Who beat villanova in 2015 in the ncaa tournament?',
  'Who beat villanova in 2014 in the ncaa tournament?',
  'Who beat villanova last year in the 2017 ncaa tournament?',
  'Who beat villanova last year in the 2015 ncaa tournament?',
  'Who beat last year in the 2014 ncaa tournament?'],
 ['Who has scored most goals in international football as men?',
  'Who has scored most goals in international football as women?'],
 ['When was the 13th amendment ratified by the required number of states?',
  'When was the 13th amendment ratified by the first group of states?'],
 ["Who is hosting the next men's FIFA world cup in 2022?",
  'Where will the next Rugby World Cup Sevens take place in 2022?'],
 ["Who played warden hodges in the original dad's army tv show, radio show, and film?",
  "Who played warden hodges in the 2016 film dad's army?",
  "Who played warden hodges in the sitcom dad's army?",
  "Who played warden hodges in the 2016 film dad's army?",
  "Who played warden hodges in the 1971 film dad's army?"],
 ["Who's the highest paid NBA player in the 2017-2018 season?",
  "Who's the highest paid NBA player in the 2016-2017 season?",
  "Who's the highest paid NBA player in the 2017-2018 season?",
  "Who's the highest paid NBA player in the 2016-2017 season?"],
 ['Who is the individual that was the leader of a 300 mile march to sacramento california?',
  'Who is the group that organized a strike and 300 mile march to sacramento california?'],
 ['Who voices Darth Vader in Star Wars Episodes III-VI, IX Rogue One, and Rebels?',
  'Who voices Darth Vader in the Star Wars radio drama?',
  "Who voices Darth Vader's vocal effects in Star Wars?"],
 ['Who do some say lived to be the oldest person in the world?',
  'Who lived to be the oldest person in the world whose age is undisputed?',
  'Who lived to be the oldest person in the world as of 1997?',
  'Who lived to be the oldest person in the world as of 1986?',
  'Who lived to be the oldest person in the world as of 1985?'],
 ['When does the 12th day of christmas begin for Eastern Christianity?',
  'When does the 12th day of christmas begin according to the commercial calendar?',
  'When does the 12th day of christmas begin in most Western ecclesiastical traditions?',
  'When does the 12 days of christmas begin?',
  'When does the final and 12th day of christmas begin?'],
 ['When did alabama became a right to work state by adopting statutes?',
  'When did alabama became a right to work state by constitutional provision?'],
 ['Who sings "I\'ll Be Seeing You" in the movie The Notebook?',
  'Who sings a version of "I\'ll Be Seeing You" in The Notebook?',
  'Who sings the version of "I\'ll Be Seeing You" that is heard second in The Notebook?',
  'Who sings the version of "I\'ll Be Seeing You that is heard first in The Notebook?'],
 ['What religious group wrote most of the New Testament?',
  'Who wrote part of the New Testament and is generally thought *not* to be a Jewish Christian?',
  'Who wrote the gospels of the New Testament?',
  'Who wrote the Pauline epistles of the New Testament?',
  'Who wrote the Epistle of James in the New Testament?',
  'Who wrote the First Epistle of Peter?'],
 ['The repetition of phrases or sentences with similar structures is called?',
  'The repetition of phrases or sentences with similar meanings is called?'],
 ['What was the last world series the cubs won before 2016?',
  'What date was the last time the cubs won the world series before 2016?'],
 ['Who plays chief superintendent Matthew Lawson on Doctor Blake Mysteries?',
  'Who plays chief superintendent William Munro on Doctor Blake Mysteries?',
  'Who plays chief superintendent Matthew Frank Carlyle on Doctor Blake Mysteries?'],
 ['What play has the line it is a tale told by an idiot full of sound and fury?',
  'What character said it is a tale told by an idiot full of sound and fury?',
  'What play has the line "it is a tale told by an idiot full of sound and fury"?',
  'What character said "it is a tale told by an idiot full of sound and fury"?'],
 ['Where does the movie 10 Things I Hate About You take place?',
  'Where was the movie 10 Things I Hate About You filmed?'],
 ['Who is opening for shania twain in ottawa on the Rock This Country Tour?',
  'Who is opening for shania twain in ottawa on the Up! Tour?',
  'Who is opening for shania twain in ottawa on the Now Tour?',
  'Who is opening for shania twain in ottawa on the Come On Over Tour?'],
 ['When does airing of last chance u season 3 airing start to take place?',
  'When does the football season for last chance u season 3 take place?',
  'When did the games of Last Chance U season 3 take place?',
  'When did the episodes of Last Chance U season 3 begin airing?'],
 ["What's the most points scored in an nba game by combined team?",
  "What's the most points scored in an nba game by a single team?",
  "What's the most points scored in an nba game by an individual?",
  'What is the highest amount of points scored by a single team in regular season NBA games?',
  'What is the highest amount of points scored by a single team in regular season games in regulation?',
  'What is the highest amount of points scored by a single team in playoff games?'],
 ['What do you use to test lipids for abnormalities?',
  'What method do you use to test for the presence of lipids?',
  'What do you use to test for lipids in food?',
  'What do you use to test for lipids in the body?'],
 ['Who co-wrote give me a home among the gum trees and also goes by the name Captain Rock?',
  'Who co-wrote give me a home among the gum trees and passed in 1995?'],
 ['Who recorded "Get Low" (which has lyrics saying "to the window, to the wall")?',
  'Who was featured on Lil Jon & the East Side Boyz\' recording of "Get Low" (which has lyrics saying "to the window, to the wall")?'],
 ['Who played Zordon in the earlier episodes of the original power rangers TV series?',
  'Who played Zordon in the later episodes of the original power rangers TV series?',
  'Who played Zordon in the original power rangers movie?'],
 ['When did construction officially start on the sydney harbour bridge?',
  'When did construction of the Arch start on the sydney harbour bridge?'],
 ['Which characters were the original twins in everybody loves raymond?',
  'Which actors were the original twins in everybody loves raymond?'],
 ['What was the name of the greatest warrior for the trojans?',
  'What was the position of the greatest warrior for the trojans?'],
 ['Who is the sheriff of Maricopa County, Arizona from 1989-93?',
  'Who is the sheriff of Maricopa County, Arizona from 1993-2017?',
  'Who is the sheriff of Maricopa County, Arizona from 2017-present?',
  'Who is the current sheriff of maricopa county arizona since 2017?',
  'Who is the sheriff of maricopa county arizona, from 1993-2017?',
  'Who is the sheriff of maricopa county arizona, from 1989-1993?'],
 ['Japanese hotel run by same family for 1300 years in Komatsu?',
  'Japanese hotel run by same family for 1300 years in Hayakawa?'],
 ['When did the US start funding/supplying the second World War in Europe?',
  'With the signing of what legislation did the US start funding/supplying the second World War in Europe?',
  'When did Roosevelt publicly confirm the "shoot on sight" order, effectively entering the US in the second world war in Europe?',
  'When did the US officially enter the second world war in europe?',
  'Upon what event did the US officially enter the second world war in europe?'],
 ["Who from Texas wrote brown eyes by destiny's child?",
  "Who from Brazil wrote brown eyes by destiny's child?"],
 ['What is the flower of the dead translated in spanish?',
  'What flower is celebrated as the flower of the dead in Mexico?'],
 ['Who do you play as in the main game of Resident Evil 7?',
  'Who do you play as in Resident Evil 7\'s downloadable content scenario "Not a Hero"?',
  'Who do you play as in Resident Evil 7\'s downloadable content scenario "End of Zoe"?'],
 ['Who serves as the president of the senate in the texas legislature in general?',
  'Who serves as the president of the senate in the texas legislature from 2015 to 2020?',
  'Who serves as the president of the senate in the texas legislature from 2003 to 2015?',
  'Who serves as the president of the senate in the texas legislature from 2000 to 2003?'],
 ['From the viewer\'s persepctive, who opened the gate to the prison, at the beginning of the walking dead\'s "Killer Within" episode?',
  'Who is the character that is discovered to have opened the gate in the prison walking dead?',
  'Who is the actor that is discovered to have opened the gate in the prison walking dead?'],
 ["Who owns green and black's organic chocolate in 2017?",
  "Who owns green and black's organic chocolate in 2005?",
  "Who owns green and black's organic chocolate in 1991?",
  "Who first owned green and black's organic chocolate?",
  "Who bought and owned green and black's organic chocolate in 2005?",
  "Who owns green and black's organic chocolate after buying it from Cadbury?"],
 ["Which political party is currently in power in ireland's Dáil Éireann from 2011 to 2016?",
  "Which political party is currently in power in ireland's Dáil Éireann from 2016 to 2020?",
  "Which political party is currently in power in ireland's presidency from 2011 to 2018?",
  "Which political party is currently in power in ireland's presidency from 2004 to 2011?",
  "Which political party is currently in power in ireland's presidency from 1997 to 2004?",
  "Which political party is currently in power in ireland's Dáil Éireann from 2007 to 2011?"],
 ['Where is the upper school of the Minnehana Academy in Minneapolis?',
  'Where is the middle and lower school of the Minnehana Academy in Minneapolis?'],
 ['Who was drafted first in the 2017 nfl draft as player?',
  'Who was the team that drafted first in the 2017 nfl draft?',
  'Who was the college that drafted first in the 2017 nfl draft?',
  'Who was the conference that drafted first in the 2017 nfl draft?'],
 ['Who wins at the end of friday night lights film?|Who wins at the end of friday night lights book?',
  'Who wins at the end of friday night lights season 5?'],
 ['What is the new name of bangalore city railway station?',
  'What is the original name of bangalore city railway station?'],
 ["Who's the team that has won the most total world series in baseball?",
  "Who's the team that has won the most consecutive world series in baseball?",
  "Who's the player that has won the most world series in baseball?",
  "Who's the manager that has won the most world series in baseball?",
  "Who's won the most world series in baseball as a player and coach combined?"],
 ['Who plays adult Eun Jae in hello my twenties series 1?',
  'Who plays young Eun Jae in hello my twenties series 1?',
  'Who plays Eun Jae in hello my twenties series 2?'],
 ['Who plays the young White Queen in the movie Alice: Through the Looking Glass?',
  'Who plays the adult White Queen in the movie Alice: Through the Looking Glass?'],
 ['Who wrote Delta of Venus (book)?',
  'Who wrote Delta of Venus (movie)?',
  'Who is the author character in the movie Delta of Venus?',
  'Who plays the author character in the movie Delta of Venus?'],
 ['What was the overall thing that led to the downfall of the incan empire?',
  'What specific thing led to the downfall of the Incan empire?',
  'What was the most devastating factor that led to the downfall of the incan empire?',
  'What was the first epidemic leading to the downfall of the incan empire?',
  'What foreign power shift helped lead to the downfall of the incan empire?'],
 ['When did the first animated Teenage Mutant Ninja Turtles cartoon series come out?',
  'When did the second teenage mutant ninja turtles animated cartoon series come out?',
  'When did the 3D rendered computer animated Teenage Mutant Ninja Turtles cartoon series come out?'],
 ['What material is Captain Americas shield made out of mostly?',
  "What are all the materials Captain America's shield  ismade out of?"],
 ['In section one of the dream of the rood what is the rood eventually drenched in beyond the gems?',
  'In section two of the dream of the rood what is the rood eventually drenched in?',

In [15]:
df['dif_questions']=dif_questions

In [16]:
df.head()

,ambiguous_question,qa_pairs,wikipages,annotations,sample_id,dif_questions
0,Who has the highest goals in world football?,"[{'context': 'No context provided', 'question'...",[{'title': 'International Federation of Footba...,"[{'knowledge': [], 'long_answer': 'Ali Dael ha...",-7013890438520559398,[Who has the highest goals in men's world inte...
1,Who is the original artist of sound of silence?,[{'context': 'Sounds of Silence is the second ...,"[{'title': 'The Sound of Silence', 'url': 'htt...",[{'knowledge': [{'content': 'Wednesday Morning...,7089015503030534342,[Who is the original artist of sound of silenc...
2,When was the first apple i phone made?,"[{'context': 'On January 9, 2007, Steve Jobs a...","[{'title': 'iPhone (1st generation)', 'url': '...",[{'knowledge': [{'content': 'The iPhone was re...,8793099883447006698,"[When was the first apple i phone released?, W..."
3,Who played the weasley brothers in harry potter?,[{'context': 'Richard Fish appeared as Bill br...,"[{'title': 'List of Harry Potter characters', ...",[{'knowledge': [{'content': 'Dozens of actors ...,-881464876144297194,[Who played Bill weasley in Harry Potter and ...
4,How many state parks are there in virginia?,"[{'context': 'No context provided', 'question'...","[{'title': 'List of Virginia state parks', 'ur...",[{'knowledge': [{'content': 'Virginia opened i...,1650309494326541834,[How many state parks are there in virginia in...

In [18]:
dev_df=df[['ambiguous_question','dif_questions']]
dev_df

,ambiguous_question,dif_questions
0,Who has the highest goals in world football?,[Who has the highest goals in men's world inte...
1,Who is the original artist of sound of silence?,[Who is the original artist of sound of silenc...
2,When was the first apple i phone made?,"[When was the first apple i phone released?, W..."
3,Who played the weasley brothers in harry potter?,[Who played Bill weasley in Harry Potter and ...
4,How many state parks are there in virginia?,[How many state parks are there in virginia in...
...,...,...
943,Where did the practice of baptism come from?,"[Where did the baptism practice come from?, Wh..."
944,Who sings the song i'm just a love machine?,"[Who sings the song ""Love Machine"" from 1975?,..."
945,When was the last time man united were in the ...,"[As of the 2016-2017 season, when was the last..."
946,Who sings beautiful girl in singin in the rain?,[Who sings beautiful girl in the 1952 stage mu...
947,Who wrote harry styles sign of the times lyrics?,[Who from Redditch wrote harry styles sign of ...

In [ ]:
query=dev_df['ambiguous_question']
dif_queries=dev_df['dif_questions']

In [ ]:
def search_documents(query, documents, model, device="cuda"):
    # 질문 임베딩 생성 (GPU로 이동)
    query_embedding = model.encode(query, convert_to_tensor=True).to(device)
    # 문서 임베딩 생성 (GPU로 이동)
    document_embeddings = model.encode(documents, convert_to_tensor=True).to(device)
    
    # 질문과 문서 간 코사인 유사도 계산 (PyTorch 기반)
    query_embedding = query_embedding.unsqueeze(0)  # 배치 차원 추가
    similarities = torch.nn.functional.cosine_similarity(query_embedding, document_embeddings)

    # 유사도에 따라 문서 정렬
    top_results = similarities.argsort(descending=True)[:5]
    print(top_results)
    res={}
    for idx in top_results:
        tmp=documents[idx]
        res[tmp]=similarities[idx]
    return list(res.items())

# 예시 사용법
for i in range(20):
    print(f"Query {i+1} : {question[i]}")
    print("-"*100)
    results = search_documents(question[i], context, model)
    print("Retrieved doc :")
    for j in range(len(results)):
        print(f"\tRank {j} : {results[j]}")
    print("Original doc :", context2[i], "\n")